<?xml version="1.0" encoding="utf-8"?>
<Project>

	<PropertyGroup>

		<TargetFramework Label="Visual Studio 2022 Target" Condition="'$(VisualStudioVersion)' == '17.0'">net8.0</TargetFramework>
		<TargetFramework Label="Default Target" Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>

		<TargetFrameworkBrowser>$(TargetFramework)-browser</TargetFrameworkBrowser>

		<Nullable>enable</Nullable>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

		<Version>26.1.1$(PreReleaseTagWithDash)</Version>

		<Product>Actipro Avalonia Controls Sample Browser</Product>
		<Title>$(Product)</Title>
		<AssemblyTitle>$(Product)</AssemblyTitle>
		<Description>Sample application to demo features of Actipro Avalonia controls.</Description>

		<RootNamespace>ActiproSoftware</RootNamespace>
		<Authors>Actipro Software LLC</Authors>
		<Copyright>Copyright (c) 2022-2026 Actipro Software LLC</Copyright>

		<DefineConstants>AVALONIA</DefineConstants>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>

	</PropertyGroup>

	<ItemGroup>
		<!-- Do not trim the common application assembly since it makes heavy use of reflection -->
		<TrimmerRootAssembly Include="SampleBrowser" />
	</ItemGroup>

</Project>