<?xml version="1.0" encoding="utf-8"?>
<!--

PUBLIC BUILD PROPERTIES

-->
<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Version>26.1.0-rc.3</Version>
		<Company>Actipro Software LLC</Company>
		<Authors>Actipro Software LLC</Authors>
		<Copyright>Copyright (c) 2021-2026 Actipro Software LLC</Copyright>
	</PropertyGroup>
</Project>