<?xml version="1.0" encoding="utf-8"?>
<Project>

	<PropertyGroup>
		<AvaloniaVersion>12.0.1</AvaloniaVersion>
		<AvaloniaUIDiagnosticsSupportVersion>2.2.0-*</AvaloniaUIDiagnosticsSupportVersion>
	</PropertyGroup>
	
	<ItemGroup Condition="$(MSBuildProjectName.Contains('.Common')) == 'true'">
		<PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*FLUENT_THEME(;.*)*$'))" />
		<PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" Condition="$([System.Text.RegularExpressions.Regex]::IsMatch($(DefineConstants), '^(.*;)*SIMPLE_THEME(;.*)*$'))" />
		
		<!-- If using the SvgImageProvider class in the Dynamic Image (SVG) sample, which supports SVG image adaptation -->
		<PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0" />
	</ItemGroup>

	<ItemGroup Condition="$(MSBuildProjectName.Contains('.Web')) == 'true'">
		<PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
	</ItemGroup>

	<ItemGroup Condition="$(MSBuildProjectName.Contains('.Desktop')) == 'true'">
		<PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
	</ItemGroup>

</Project>