//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiproSoftware.Properties.Bars.Mvvm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiproSoftware.Properties.Bars.Mvvm.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string UIApplicationButtonText {
            get {
                return ResourceManager.GetString("UIApplicationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fonts.
        /// </summary>
        public static string UIGalleryItemCategoryAllFontsText {
            get {
                return ResourceManager.GetString("UIGalleryItemCategoryAllFontsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Sizes.
        /// </summary>
        public static string UIGalleryItemCategoryFontSizesText {
            get {
                return ResourceManager.GetString("UIGalleryItemCategoryFontSizesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Colors.
        /// </summary>
        public static string UIGalleryItemCategoryStandardColorsText {
            get {
                return ResourceManager.GetString("UIGalleryItemCategoryStandardColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string UIGalleryItemCategorySymbols {
            get {
                return ResourceManager.GetString("UIGalleryItemCategorySymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Highlight Colors.
        /// </summary>
        public static string UIGalleryItemCategoryTextHighlightColorsText {
            get {
                return ResourceManager.GetString("UIGalleryItemCategoryTextHighlightColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Styles.
        /// </summary>
        public static string UIGalleryItemCategoryTextStylesText {
            get {
                return ResourceManager.GetString("UIGalleryItemCategoryTextStylesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Colors.
        /// </summary>
        public static string UIGalleryItemCategoryThemeColorsText {
            get {
                return ResourceManager.GetString("UIGalleryItemCategoryThemeColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string UINamedColorBlackText {
            get {
                return ResourceManager.GetString("UINamedColorBlackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Gray.
        /// </summary>
        public static string UINamedColorBlueGrayText {
            get {
                return ResourceManager.GetString("UINamedColorBlueGrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string UINamedColorBlueText {
            get {
                return ResourceManager.GetString("UINamedColorBlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Green.
        /// </summary>
        public static string UINamedColorBrightGreenText {
            get {
                return ResourceManager.GetString("UINamedColorBrightGreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        public static string UINamedColorDarkBlueText {
            get {
                return ResourceManager.GetString("UINamedColorDarkBlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Red.
        /// </summary>
        public static string UINamedColorDarkRedText {
            get {
                return ResourceManager.GetString("UINamedColorDarkRedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Yellow.
        /// </summary>
        public static string UINamedColorDarkYellowText {
            get {
                return ResourceManager.GetString("UINamedColorDarkYellowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string UINamedColorGoldText {
            get {
                return ResourceManager.GetString("UINamedColorGoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray-25%.
        /// </summary>
        public static string UINamedColorGray25Text {
            get {
                return ResourceManager.GetString("UINamedColorGray25Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray-50%.
        /// </summary>
        public static string UINamedColorGray50Text {
            get {
                return ResourceManager.GetString("UINamedColorGray50Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string UINamedColorGrayText {
            get {
                return ResourceManager.GetString("UINamedColorGrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string UINamedColorGreenText {
            get {
                return ResourceManager.GetString("UINamedColorGreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        public static string UINamedColorLightBlueText {
            get {
                return ResourceManager.GetString("UINamedColorLightBlueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Gray.
        /// </summary>
        public static string UINamedColorLightGrayText {
            get {
                return ResourceManager.GetString("UINamedColorLightGrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Green.
        /// </summary>
        public static string UINamedColorLightGreen {
            get {
                return ResourceManager.GetString("UINamedColorLightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string UINamedColorOrangeText {
            get {
                return ResourceManager.GetString("UINamedColorOrangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string UINamedColorPinkText {
            get {
                return ResourceManager.GetString("UINamedColorPinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string UINamedColorPurpleText {
            get {
                return ResourceManager.GetString("UINamedColorPurpleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string UINamedColorRedText {
            get {
                return ResourceManager.GetString("UINamedColorRedText", resourceCulture);
            }
        }
    }
}
