<?xml version="1.0" encoding="utf-8"?>
<!--

PUBLIC\SOURCE BUILD PROPERTIES

-->
<Project>

	<!-- Merge in parent folder's Directory.Build.props file -->
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

	<PropertyGroup>

		<TargetFrameworks Label="Visual Studio 2022 Targets" Condition="'$(BuildingInsideVisualStudio)' == 'true' and '$(VisualStudioVersion)' == '17.0'">net8.0</TargetFrameworks>
		<TargetFrameworks Label="Default Targets" Condition="'$(TargetFrameworks)' == ''">net10.0;net8.0</TargetFrameworks>

		<Nullable>enable</Nullable>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

		<RootNamespace>ActiproSoftware</RootNamespace>

		<DefineConstants>CODE_ANALYSIS;AVALONIA</DefineConstants>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageProjectUrl>https://www.actiprosoftware.com/products/controls/avalonia</PackageProjectUrl>

		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
	</PropertyGroup>

</Project>